services:
    # Core
    apy_grid.factory:
        class: APY\DataGridBundle\Grid\GridFactory
        arguments: ['@service_container', '@apy_grid.registry']
        public: true
    apy_grid.registry:
        class: APY\DataGridBundle\Grid\GridRegistry
        public: true

    # Types
    apy_grid.type.grid:
        class: APY\DataGridBundle\Grid\Type\GridType
        public: true
        tags:
            - { name: apy_grid.type }

    # Columns
    apy_grid.column.text:
        class: APY\DataGridBundle\Grid\Column\TextColumn
        public: true
        tags:
            - { name: apy_grid.column }
    apy_grid.column.array:
        class: APY\DataGridBundle\Grid\Column\ArrayColumn
        public: true
        tags:
            - { name: apy_grid.column }
    apy_grid.column.blank:
        class: APY\DataGridBundle\Grid\Column\BlankColumn
        public: true
        tags:
            - { name: apy_grid.column }
    apy_grid.column.boolean:
        class: APY\DataGridBundle\Grid\Column\BooleanColumn
        public: true
        tags:
            - { name: apy_grid.column }
    apy_grid.column.date:
        class: APY\DataGridBundle\Grid\Column\DateColumn
        public: true
        tags:
            - { name: apy_grid.column }
    apy_grid.column.date_time:
        class: APY\DataGridBundle\Grid\Column\DateTimeColumn
        public: true
        tags:
            - { name: apy_grid.column }
    apy_grid.column.join:
        class: APY\DataGridBundle\Grid\Column\JoinColumn
        public: true
        tags:
            - { name: apy_grid.column }
    apy_grid.column.number:
        class: APY\DataGridBundle\Grid\Column\NumberColumn
        public: true
        tags:
            - { name: apy_grid.column }
    apy_grid.column.rank:
        class: APY\DataGridBundle\Grid\Column\RankColumn
        public: true
        tags:
            - { name: apy_grid.column }
    apy_grid.column.time:
        class: APY\DataGridBundle\Grid\Column\TimeColumn
        public: true
        tags:
            - { name: apy_grid.column }
